const logoUrl = new URL('../components/impexlogo.png', import.meta.url).href;

function getCompanyInfo() {
  try {
    const raw = localStorage.getItem('company_info');
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function printHtml(title: string, bodyHtml: string) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;

  const company = getCompanyInfo();
  const companyHtml = company
    ? `
      <div class="company">
        <div class="company-name">${company.name || ''}</div>
        <div class="company-meta">${company.address || ''}</div>
        <div class="company-meta">${company.phone || ''}</div>
        <div class="company-meta">${company.email || ''}</div>
        <div class="company-meta">${company.website || ''}</div>
        <div class="company-meta">${company.tin || ''}</div>
      </div>
    `
    : '';

  doc.open();
  doc.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          @page { size: auto; margin: 8mm; }
          body { font-family: Arial, sans-serif; color: #111; margin: 0; }
          .page { padding: 0; }
          .header { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; align-items: flex-start; border-bottom: 1px solid #e5e7eb; padding-bottom: 12px; margin-bottom: 16px; }
          .header .logo { display: flex; align-items: center; }
          .header img { width: 220px; height: auto; object-fit: contain; }
          .company { font-size: 12px; color: #111; line-height: 1.35; text-align: right; }
          .company-name { font-weight: bold; font-size: 13px; letter-spacing: 0.2px; }
          .company-meta { margin-top: 2px; }
          h1 { font-size: 22px; margin: 6px 0 10px; }
          h2 { font-size: 16px; margin: 8px 0 6px; }
          h3 { font-size: 13px; margin: 8px 0 6px; }
          .doc-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin: 10px 0 12px; font-size: 12px; }
          .doc-meta div { color: #444; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
          th, td { border-bottom: 1px solid #e5e7eb; padding: 8px 6px; }
          th { text-align: left; font-weight: 600; background: #f9fafb; }
          .meta { margin: 4px 0; font-size: 12px; color: #555; }
          .meta-inline { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
          .meta-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 6px 16px; margin: 10px 0 12px; }
          .meta-full { grid-column: 1 / -1; }
          .total { text-align: right; font-weight: bold; margin-top: 12px; }
          .footer { border-top: 1px solid #e5e7eb; margin-top: 10px; padding-top: 8px; font-size: 11px; color: #666; }
          .doc-label { font-weight: 600; color: #111; }
          .doc-code { border: 1px dashed #cbd5f5; background: #f8fafc; padding: 4px 8px; font-size: 12px; display: inline-block; vertical-align: middle; }
        </style>
      </head>
      <body>
        <div class="page">
          <div class="header">
            <div class="logo">
              <img src="${logoUrl}" alt="ImpexLink Logo" />
            </div>
            ${companyHtml}
          </div>
          ${bodyHtml}
        </div>
        <div class="footer">
          Generated by ImpexLink - ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `);
  doc.close();
  iframe.contentWindow?.focus();
  setTimeout(() => {
    iframe.contentWindow?.print();
    document.body.removeChild(iframe);
  }, 300);
}
